server:
  port: 8805
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    max-connections: 100

spring:
  application:
    name: docker
  datasource:
    agent:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://10.20.4.194:1433;DatabaseName=interface-agent;encrypt=false;trustServerCertificate=false
      username: sa
      password: Hjk@2022!@
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      validation-query: select 1
      test-while-idle: true